### ISSUE TITLE
他の軸方向の画像の再構成

### ISSUE THREAD

**Issue by kenya-sk** [kenya-sk/CIP#15]
３次元でのオプテイカルフロー問題解消のために、別の軸を基準とした画像を再構成する

**Comment by MitsukiUsui** [comment]
"別の軸"とは？

**Comment by kenya-sk** [comment]
y軸固定で、x-z軸方向の画像を生成予定
x-y方向（元画像）の分解能0.25μm, z方向の分解能1μmとの情報が与えられているので、そこまで飛び飛びの画像にならないかとのことです。

**Comment by MitsukiUsui** [comment]
いんてれすてぃんぐ
目的はよくわからないけど
分解能与えられてるのに可視化する必要ある？



----- Thursday, August 31st -----
sakka [12:24 AM] 
新たに生成された画像を用いて、2次元のオプティカルフローと同じ手法（関数）でz軸方向の動きも取れるようになるので、新たに3次元のオプティカルフローを実装する必要がなくなるかと。。


mitsuki [10:32 PM] 
うーーん。なるほど。面白い観点だと思ったけど、例えばyzで画像を作ったとすると、すでにx方向でのブレが補正されていることが前提になるよね。つまり① xy方向での補正②yz方向での補正の2段階のオプティカルフローの補正が必要になるんだけど、それは少しスマートではないように思う。 (edited)

今回レベル2の補正が上手くいっているのは、z方向のブレがほぼないことが保証されていてxy方向の補正のみを考えれば良い問題設定になっているからです。

xyz全てにブレがあるようなケースだと、xy方向から始めても、yz方向から始めても、どちらの仮定も満たせないから上手くいかないと思う。

どうしてもテンプレートマッチを3次元に行う必要があると考えている。
