### ISSUE TITLE
mask dense flow before calculation of cumulative flow

### ISSUE THREAD

**Issue by takebiolac** [kenya-sk/CIP#52]

**Comment by MitsukiUsui** [comment]
cumulative flowを元に細胞分裂を検出しようとしているが、対象のブレによって画面から外れてしまう領域のdense flowが大きくなる影響で、画面周辺のcumulative flowも大きくなり、細胞分裂が見つけにくいという問題点があった。2フレーム間のどちらでも画面内に入っている領域のみでdense flowを加算するようなmask機能をcumulative_flow.py内に実装する。
