### ISSUE TITLE
提出用にフォーマットを整える。

### ISSUE THREAD

**Issue by MitsukiUsui** [kenya-sk/CIP#78]
autopep8 --max-line-length=1000
ログメッセージの質とか。まぁやらなくてもいいかも。

**Comment by MitsukiUsui** [comment]
あとbranchがもじゃもじゃ生えてる

**Comment by MitsukiUsui** [comment]
必要なコマンドの手順をREADMEにかけると嬉しい。（俺は忘れてしまった）

**Comment by takebiolac** [comment]
branch は消した。
